### ISSUE TITLE
Rename to vercel-sapper?

### ISSUE THREAD

**Issue by benmccann** [thgh/now-sapper#25]
There's a PR (https://github.com/sveltejs/sapper/pull/1199) that's suggesting to add this plugin to the Sapper docs along with updating all references of "Now" to "Vercel". I'm wondering if you'll be doing the same because if the link to this repo or name of the npm package is going to change we should capture that

**Comment by antony** [comment]
`now` is the product name, which hasn't changed. Vercel is the company name :)

**Comment by antony** [comment]
As mentioned in the other issue, looks like they went ahead and confusingly renamed `Zeit`, the company which had the infra product `now` to `Vercel` and now the whole thing is just called `Vercel`.

We should probably rename this, I don't think there's huge urgency though since in their docs all the other community builders are still prefixed with `now-`:

https://vercel.com/docs/runtimes#advanced-usage/community-runtimes

**Comment by thgh** [comment]
OK, let's wait for a recommendation from Vercel.

**Comment by antony** [comment]
I think if somebody opens a PR to fix all the references it will be ok to rename this. We could publish the `now` and `vercel` versions in parallel until their transition is finished.

Their site/docs say that everything is just now called `vercel`, and they plan to rename everything, but have both `now` and `vercel` versions for the near term.

**Comment by thgh** [comment]
The project has been renamed. The source code for [now-sapper is here](https://github.com/thgh/now-sapper/tree/now).

Interesting timeline: https://www.notion.so/Change-Timeline-fab7622780694753a92c0a396cea7eb6
